## Build command:  docker build --no-cache -t acquiflow -f Dockerfile.old --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN .

FROM ubuntu:24.04  AS base

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /rails

RUN apt-get update  && apt-get install -y \
    curl \
    build-essential \
    git \
    wget \
    # libyaml-dev \
    zlib1g-dev \
    libpq-dev \
    shared-mime-info \
    # libgmp-dev \
    # libreadline-dev \
    # libffi-dev \
    # libncurses5-dev \
    && rm -rf /var/lib/apt/lists/*

FROM base AS build

RUN curl https://mise.run | sh
ENV PATH="/root/.local/bin:/root/.local/share/mise/shims:${PATH}"

RUN mise settings ruby.compile=false && \
    mise settings legacy_version_file=true && \
    mise use -g ruby@${RUBY_VERSION}
